import { Injectable } from '@nestjs/common';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require('pdfkit') as typeof import('pdfkit');
import { DocumentData } from '../interfaces/document-generator.interface';

@Injectable()
export class PdfGenerator {
  generate(data: DocumentData, textContent: string): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 60,
        info: {
          Title: data.title,
          Author: data.generatedBy,
          Subject: `Notarial Document ${data.documentNumber}`,
          CreationDate: new Date(data.generatedAt),
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      this.renderHeader(doc, data);
      this.renderClient(doc, data);
      this.renderServices(doc, data);
      this.renderFooter(doc, data);

      doc.end();
    });
  }

  private renderHeader(doc: PDFKit.PDFDocument, data: DocumentData): void {
    doc
      .fontSize(18)
      .font('Helvetica-Bold')
      .text('NOTARIAL DOCUMENT', { align: 'center' })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(`Document No: ${data.documentNumber}`, { align: 'center' })
      .text(`Title: ${data.title}`, { align: 'center' })
      .text(
        `Generated: ${new Date(data.generatedAt).toLocaleDateString('uk-UA')}`,
        { align: 'center' },
      )
      .text(`Notary: ${data.generatedBy}`, { align: 'center' })
      .moveDown();

    this.drawHorizontalLine(doc);
  }

  private renderClient(doc: PDFKit.PDFDocument, data: DocumentData): void {
    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('CLIENT INFORMATION')
      .moveDown(0.3);

    doc.fontSize(10).font('Helvetica');

    const fields: [string, string][] = [
      ['Full Name', data.client.fullName],
      ['National ID', data.client.nationalId],
      ['Date of Birth', new Date(data.client.dateOfBirth).toLocaleDateString('uk-UA')],
      ['Address', data.client.address],
      ['Phone', data.client.phone],
    ];

    if (data.client.email) fields.push(['Email', data.client.email]);
    if (data.verificationStatus) {
      fields.push(['Identity Verification', data.verificationStatus]);
    }

    for (const [label, value] of fields) {
      doc
        .font('Helvetica-Bold')
        .text(`${label}: `, { continued: true })
        .font('Helvetica')
        .text(value);
    }

    doc.moveDown();
    this.drawHorizontalLine(doc);
  }

  private renderServices(doc: PDFKit.PDFDocument, data: DocumentData): void {
    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('SERVICES')
      .moveDown(0.3);

    let total = 0;

    data.services.forEach((service, index) => {
      const fee = service.feeAmount / 100;
      total += service.feeAmount;

      doc
        .fontSize(10)
        .font('Helvetica-Bold')
        .text(`${index + 1}. [${service.type}]`)
        .font('Helvetica')
        .text(`   ${service.description}`)
        .text(`   Fee: ${fee.toFixed(2)} ${service.feeCurrency}`);

      if (service.confirmedAt) {
        doc.text(
          `   Confirmed: ${new Date(service.confirmedAt).toLocaleDateString('uk-UA')}`,
        );
      }

      doc.moveDown(0.5);
    });

    const currency = data.services[0]?.feeCurrency ?? 'UAH';
    doc.moveDown(0.5);
    this.drawHorizontalLine(doc);
    doc
      .fontSize(11)
      .font('Helvetica-Bold')
      .text(`TOTAL FEE: ${(total / 100).toFixed(2)} ${currency}`)
      .moveDown();

    if (data.notes) {
      doc
        .fontSize(10)
        .font('Helvetica-Bold')
        .text('NOTES:')
        .font('Helvetica')
        .text(data.notes)
        .moveDown();
    }

    this.drawHorizontalLine(doc);
  }

  private renderFooter(doc: PDFKit.PDFDocument, data: DocumentData): void {
    doc.moveDown(2);
    doc
      .fontSize(10)
      .font('Helvetica')
      .text('Notary signature: ____________________________', { align: 'left' })
      .moveDown()
      .text(`Date: ________________`, { align: 'left' });

    // Page number
    doc
      .fontSize(8)
      .text(
        `Generated by Notary CRM — ${new Date(data.generatedAt).toISOString()}`,
        0,
        doc.page.height - 40,
        { align: 'center', width: doc.page.width },
      );
  }

  private drawHorizontalLine(doc: PDFKit.PDFDocument): void {
    doc
      .moveTo(doc.page.margins.left, doc.y)
      .lineTo(doc.page.width - doc.page.margins.right, doc.y)
      .strokeColor('#cccccc')
      .stroke()
      .moveDown(0.5);
  }
}
